- platform: generic_thermostat
  name: Bedroom Climate
  heater: switch.bed_ac_power_switch_switch_unsafe
  ac_mode: true
  target_temp: 78
  hot_tolerance: 3.0
  min_cycle_duration:
    minutes: 5
  target_sensor: sensor.bedroom_temperature
  initial_hvac_mode: "off"
  precision: 0.1
