
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  customize:
    switch.bed_ac_power_switch_switch_unsafe:
      hidden: true

zwave:
  usb_path: /dev/ttyUSB0

# Text to speech
tts:
  - platform: google_translate

timer:
  bed_ac_lockout:
    duration: '00:03:00'
    icon: 'mdi:lock-clock'

switch:
  - platform: template 
    switches:
      bedroom_ac_safe:
        availability_template: "{{ not is_state('timer.bed_ac_lockout', 'active') }}"
        value_template: "{{ is_state('switch.bed_ac_power_switch_switch_unsafe', 'on') }}"
        friendly_name: Bedroom AC
        turn_on:
          service: switch.turn_on
          data:
            entity_id: switch.bed_ac_power_switch_switch_unsafe
        turn_off:
          service: switch.turn_off
          data:
            entity_id: switch.bed_ac_power_switch_switch_unsafe

cloud:
  google_actions:
    filter:
      include_entities:
        - switch.bedroom_ac_safe
        - switch.stage_lights
    entity_config:
      switch.bedroom_ac_safe:
        name: Bedroom AC 
        aliases:
         - bedroom air conditioning
         - bedroom air conditioner 
  alexa:
    filter:
      include_entities:
        - switch.bedroom_ac_safe
        - switch.stage_lights
    entity_config:
      switch.bedroom_ac_safe:
        name: Bedroom AC 

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
