
default_config:

homeassistant:
  customize:
    switch.bed_ac_power_switch_switch_unsafe:
      hidden: true

zwave:
  usb_path: /dev/ttyUSB0

tts:
  - platform: google_translate

timer:
  bed_ac_lockout:
    duration: '00:03:00'
    icon: 'mdi:lock-clock'

automation: !include_dir_merge_list automation/
climate: !include climate.yaml
cloud: !include cloud.yaml
group: !include groups.yaml
scene: !include scenes.yaml
script: !include_dir_merge_named script/
sensor: !include_dir_merge_list sensor/
shell_command: !include_dir_merge_named shell_command/
switch: !include_dir_merge_list switch/
